# Generated by Django 3.0.8 on 2020-07-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='other', max_length=10),
            preserve_default=False,
        ),
    ]
