# Generated by Django 3.0.8 on 2020-07-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('FE', 'frontend'), ('BE', 'backend'), ('FS', 'fullstack'), ('OT', 'other')], default='OT', max_length=10),
        ),
    ]
