# Generated by Django 3.0.8 on 2020-07-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200729_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Frontend', 'FE'), ('Backend', 'BE'), ('Fullstack', 'FS'), ('Other', 'OT')], default='Other', max_length=10),
        ),
    ]
